#!/bin/bash

echo "🔍 Checking what's actually deployed..."
echo ""
echo "Please run these commands in Telegram to diagnose:"
echo ""
echo "1. Send: /admin"
echo "   This will show your chat ID and admin status"
echo ""
echo "2. Send: /setadmin agami2024"
echo "   This will force you to become admin"
echo ""
echo "3. Send: /delete 0"
echo "   This should now work"
echo ""
echo "If /setadmin command doesn't exist, it means the old code is still deployed!"
echo ""
echo "To check if new code is deployed:"
echo "- If /setadmin returns 'Unknown command' = OLD CODE"
echo "- If /setadmin asks for secret = NEW CODE"
echo ""
echo "📝 The issue is that the FIXED code hasn't been deployed to Cloudflare yet."