name = "agaminews"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# Add your Telegram bot token in Cloudflare dashboard

[[kv_namespaces]]
binding = "NEWS_KV"
id = "YOUR_KV_ID"
preview_id = "YOUR_KV_ID"

[site]
bucket = "./public"

[triggers]
crons = ["0 */6 * * *"]