name = "agaminews"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
WORKER_URL = "https://agaminews.workers.dev"

[[kv_namespaces]]
binding = "NEWS_KV"
id = "WILL_BE_CREATED"
preview_id = "WILL_BE_CREATED"

[triggers]
crons = ["0 */6 * * *"]