name = "agaminews"
main = "index.js"
compatibility_date = "2024-01-01"

[vars]
WORKER_URL = "https://agaminews.workers.dev"

[[kv_namespaces]]
binding = "NEWS_KV"
id = "72c0dad910574e7cb4bd8bb5918af847"
preview_id = "72c0dad910574e7cb4bd8bb5918af847"

[triggers]
crons = ["0 */6 * * *"]