name = "agaminews"
main = "worker/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

# These routes will bind the worker to your domain
route = { pattern = "agaminews.in/*", zone_name = "agaminews.in" }

[vars]
ENVIRONMENT = "production"