name = "telegram-mcq-bot-wahid"
main = "worker/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

routes = [
  { pattern = "agaminews.in/*", zone_name = "agaminews.in" },
  { pattern = "www.agaminews.in/*", zone_name = "agaminews.in" }
]

[vars]
ENVIRONMENT = "production"