name = "agaminews"
main = "index.js"
compatibility_date = "2024-01-01"

# Routes - make sure these match your domain setup
[[routes]]
pattern = "agaminews.in/*"
zone_name = "agaminews.in"

[[routes]]  
pattern = "www.agaminews.in/*"
zone_name = "agaminews.in"

# Environment variables
[vars]
ENVIRONMENT = "production"

# KV will be created dynamically if needed
# Remove the KV namespace binding to avoid errors