name = "ai-website-manager"
main = "index.js"
compatibility_date = "2024-01-01"

# Routes - ensure deployment to correct domain
routes = [
  { pattern = "agaminews.in/*", zone_name = "agaminews.in" },
  { pattern = "www.agaminews.in/*", zone_name = "agaminews.in" }
]

# KV Namespace binding
[[kv_namespaces]]
binding = "NEWS_KV"
id = "72c0dad910574e7cb4bd8bb5918af847"

# Cron trigger for automatic updates
[triggers]
crons = ["0 */2 * * *"]

[vars]
ENVIRONMENT = "production"

# These will be set via wrangler secret
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# OPENAI_API_KEY
# GITHUB_TOKEN
# GITHUB_REPO