name = "telegram-mcq-bot-wahid"
main = "index.js"
compatibility_date = "2024-01-01"

# Route is configured in Cloudflare Dashboard
# Worker: agaminews

# KV Namespace binding
[[kv_namespaces]]
binding = "NEWS_KV"
id = "72c0dad910574e7cb4bd8bb5918af847"

# Cron trigger for automatic updates
[triggers]
crons = ["0 */2 * * *"]

[vars]
ENVIRONMENT = "production"

# These will be set via wrangler secret
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# OPENAI_API_KEY
# GITHUB_TOKEN
# GITHUB_REPO