name = "agaminews"
main = "index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "NEWS_KV"
id = "NEWS_KV"

[vars]
ENVIRONMENT = "production"

# Secrets are set via wrangler or dashboard:
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# OPENAI_API_KEY
# GITHUB_TOKEN
# GITHUB_REPO