name = "ai-website-manager"
main = "index.js"
compatibility_date = "2024-01-01"

# Your custom domain
routes = [
  { pattern = "agaminews.in/*", custom_domain = true },
  { pattern = "www.agaminews.in/*", custom_domain = true }
]

# KV Namespace binding - will be set via GitHub secrets
# [[kv_namespaces]]
# binding = "NEWS_KV"
# id = "YOUR_KV_ID"

# Cron trigger for automatic updates
[triggers]
crons = ["0 */2 * * *"]

[vars]
ENVIRONMENT = "production"

# These will be set via wrangler secret
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# OPENAI_API_KEY
# GITHUB_TOKEN
# GITHUB_REPO