name = "ai-website-manager"
main = "deploy-this.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "NEWS_KV"
id = "acf08b0c797e41eeac717297ac9d7f7d"

# Cron trigger for automatic updates
[triggers]
crons = ["0 */2 * * *"]

[vars]
ENVIRONMENT = "production"

# These will be set via wrangler secret
# TELEGRAM_BOT_TOKEN
# TELEGRAM_CHAT_ID
# OPENAI_API_KEY
# GITHUB_TOKEN
# GITHUB_REPO