name: Backup Cron Trigger

on:
  schedule:
    # Run every 3 hours as backup
    - cron: '0 */3 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  trigger-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Worker Cron
        run: |
          response=$(curl -X GET "https://agaminews.in/trigger?key=agami2024" \
            -H "Content-Type: application/json" \
            --max-time 30 \
            --write-out "\n%{http_code}" \
            --silent \
            --output -)
          
          http_code=$(echo "$response" | tail -n 1)
          body=$(echo "$response" | sed '$d')
          
          echo "Response: $body"
          echo "HTTP Code: $http_code"
          
          if [ "$http_code" != "200" ]; then
            echo "Failed to trigger cron"
            exit 1
          fi