name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Check environment
        run: |
          echo "Checking deployment environment..."
          echo "Has API Token: ${{ secrets.CLOUDFLARE_API_TOKEN && 'YES' || 'NO' }}"
          echo "Has Account ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID && 'YES' || 'NO' }}"
          echo "Worker directory contents:"
          ls -la worker/
          echo "Wrangler.toml contents:"
          cat worker/wrangler.toml
      
      - name: Install Wrangler
        run: npm install --no-fund --no-audit --save-dev wrangler@4

      - name: Print versions
        run: |
          node -v
          npx wrangler --version

      - name: Deploy to Cloudflare Workers (npx)
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: npx wrangler deploy --config worker/wrangler.toml --log-level warn